export const ATLAN_PUBLIC_QUERY_CLASSIFICATION = 'PzzjpKQXGWftJfe4LV5AzI'

export const LINE_ERROR_NAMES = ['VALIDATION_ERROR', 'QUERY_PARSING_ERROR']
export const SOURCE_ACCESS_ERROR_NAMES = ['FORBIDDEN']
