/* Business Metadata */
export const BUSINESS_METADATA_SET_LIST = "BUSINESS_METADATA_SET_LIST";
export const BUSINESS_METADATA_SET_ERROR = "BUSINESS_METADATA_SET_ERROR";
export const BUSINESS_METADATA_SET_LOADING = "BUSINESS_METADATA_SET_LOADING";
export const USER_FETCH_BULK_USERS_IF_NOT_AVAILABLE =
  "USER_FETCH_BULK_USERS_IF_NOT_AVAILABLE";
export const BUSINESS_METADATA_APPEND_TO_LIST =
  "BUSINESS_METADATA_APPEND_TO_LIST";
export const BUSINESS_METADATA_UPDATE_BUSINESS_METADATA_IN_LIST =
  "BUSINESS_METADATA_UPDATE_BUSINESS_METADATA_IN_LIST";
export const BUSINESS_METADATA_GET_BUSINESS_METADATA_ATTRIBUTES_FOR_TYPENAMES =
  "BUSINESS_METADATA_GET_BUSINESS_METADATA_ATTRIBUTES_FOR_TYPENAMES";
export const BUSINESS_METADATA_GET_BUSINESS_METADATA_ATTRIBUTES_NAMES =
  "BUSINESS_METADATA_GET_BUSINESS_METADATA_ATTRIBUTES_NAMES";
export const BUSINESS_METADATA_GET_ATTRIBUTE_PROJECTION =
  "BUSINESS_METADATA_GET_ATTRIBUTE_PROJECTION";
