export enum ActionTypes {
  RESET_CLASSIFICATIONS = "RESET_CLASSIFICATIONS",
  CREATE_CLASSIFICATION = "CREATE_CLASSIFICATION",
  GET_CLASSIFICATIONS = "GET_CLASSIFICATIONS",
  UPDATE_CLASSIFICATION_LIST_BY_ID = "UPDATE_CLASSIFICATIONS_LIST_BY_ID",
  SET_CLASSIFICATIONS = "SET_CLASSIFICATIONS",
  UPDATE_CLASSIFICATION_TREE = "UPDATE_CLASSIFICATION_TREE",
  SET_CLASSIFICATION_STATUS = "SET_CLASSIFICATION_STATUS",
  FILTER_CLASSIFICATION_TREE = "FILTER_CLASSIFICATION_TREE",
  DELETE_CLASSIFICATION_BY_NAME = "DELETE_CLASSIFICATION_BY_NAME",
}
