export const MODULE_LIST_GROUP = "list_group";
export const FETCH_GROUP_LIST = "FETCH_GROUP_LIST";
export const GROUP_UPDATE_GROUP = "GROUP_UPDATE_GROUP";
export const SET_ACTIVE_GROUP_ID = "SET_ACTIVE_GROUP_ID";
export const GET_GROUP_BY_ID = "GET_GROUP_BY_ID";
export const SET_GROUP_SEARCH_STRING = "SET_GROUP_SEARCH_STRING";

export const SET_GROUP_LIST = "SET_GROUP_LIST";

export const SET_TOTAL_GROUPS_COUNT = "SET_TOTAL_GROUPS_COUNT";
export const SET_GROUP_LIST_STATUS = "SET_GROUP_LIST_STATUS";
export const ACTIVE_GROUP = "ACTIVE_GROUP";
export const TOGGLE_ADD_GROUP_MODAL = "TOGGLE_ADD_GROUP_MODAL";


//refactoring 
export const GET_GROUP_LIST = "GET_GROUP_LIST";
export const FILTER_GROUP_LIST = "FILTER_GROUP_LIST";
export const SET_GROUP_LIST_API_PARAMS = "SET_GROUP_LIST_API_PARAMS";