export const SEARCH_SET_LIST = "SEARCH_SET_LIST";
export const SEARCH_SET_STATUS = "SEARCH_SET_STATUS";
export const SEARCH_SET_SEARCH = "SEARCH_SET_SEARCH";
export const SEARCH_FETCH_LIST = "SEARCH_FETCH_LIST";