export const EVENT_QUERY_RUN = "EVENT_QUERY_RUN";
export const EVENT_GLOBAL_SEARCH_OPEN_KEYBOARD_SHORTCUT =
  "EVENT_GLOBAL_SEARCH_OPEN_KEYBOARD_SHORTCUT";
export const EVENT_QUERY_SAVED = "EVENT_QUERY_SAVED";
export const EVENT_SEARCH_SAVED = "EVENT_SEARCH_SAVED";
export const EVENT_GLOSSARY_SEARCH = "EVENT_GLOSSARY_SEARCH";
export const EVENT_GLOSSARY_CREATION = "EVENT_GLOSSARY_CREATION";
export const EVENT_GLOSSARY_TERM_CREATION = "EVENT_GLOSSARY_TERM_CREATION";
export const EVENT_GLOSSARY_CATEGORY_CREATION =
  "EVENT_GLOSSARY_CATEGORY_CREATION";
export const EVENT_CLASSIFICATION_CREATION = "EVENT_CLASSIFICATION_CREATION";
export const EVENT_ASSET_OWNER_UPDATED = "EVENT_ASSET_OWNER_UPDATED";
export const EVENT_ASSET_EXPERT_UPDATED = "EVENT_ASSET_EXPERT_UPDATED";
export const EVENT_GLOSSARY_TERM_LINKED = "EVENT_GLOSSARY_TERM_LINKED";
export const EVENT_CLASSIFICATION_LINKED = "EVENT_CLASSIFICATION_LINKED";
export const EVENT_README_ADDED = "EVENT_README_ADDED";
export const EVENT_README_EDITED = "EVENT_README_EDITED";
export const EVENT_CHAT_OPENED = "EVENT_CHAT_OPENED";
export const EVENT_CHAT_MESSAGE_SENT = "EVENT_CHAT_MESSAGE_SENT";
export const EVENT_IMPACTED_ASSET_DOWNLOADED =
  "EVENT_IMPACTED_ASSET_DOWNLOADED";
export const EVENT_NEW_USER_ADDED = "EVENT_NEW_USER_ADDED";
export const EVENT_GROUP_CREATED = "EVENT_GROUP_CREATED";
export const EVENT_POLICY_CREATED = "EVENT_POLICY_CREATED";
export const EVENT_APIKEY_CREATED = "EVENT_APIKEY_CREATED";
export const EVENT_REQUEST_APPROVED_DECLINED =
  "EVENT_REQUEST_APPROVED_DECLINED";
export const EVENT_LINEAGE_TREEVIEW_OPENED = "EVENT_LINEAGE_TREEVIEW_OPENED";
export const EVENT_LINEAGE_GRAPHVIEW_OPENED = "EVENT_LINEAGE_GRAPHVIEW_OPENED";
export const EVENT_ASSET_DESCRIPTION_UPDATED =
  "EVENT_ASSET_DESCRIPTION_UPDATED";
export const EVENT_GLOSSARY_TERM_DESCRIPTION_UPDATED =
  "EVENT_GLOSSARY_TERM_DESCRIPTION_UPDATED";
export const EVENT_ASSET_SEARCH = "EVENT_ASSET_SEARCH";
export const EVENT_GLOSSARY_TERM_CREATION_BULK =
  "EVENT_GLOSSARY_TERM_CREATION_BULK";
export const EVENT_GLOSSARY_CATEGORY_CREATION_BULK =
  "EVENT_GLOSSARY_CATEGORY_CREATION_BULK";
export const EVENT_TOP_FIVE_SEARCH_RESULTS_CLICKED =
  "EVENT_TOP_FIVE_SEARCH_RESULTS_CLICKED";

export const EVENT_GTC_OWNER_UPDATED = "EVENT_GTC_OWNER_UPDATED";
export const EVENT_GTC_EXPERT_UPDATED = "EVENT_GTC_EXPERT_UPDATED";

/* Slack events */
export const SLACK_NOTIFICATION_CHAT_USER_MENTION =
  "EVENT_SLACK_NOTIFICATION_CHAT_USER_MENTION";
export const SLACK_NOTIFICATION_CHAT_SLACK_CHANNEL_MENTION =
  "EVENT_SLACK_NOTIFICATION_CHAT_SLACK_CHANNEL_MENTION";
export const SLACK_SHARE_ON_CHANNEL = "EVENT_SLACK_SHARE_ON_CHANNEL";
export const SLACK_DELETE_INTEGRATION = "EVENT_SLACK_DELETE_INTEGRATION";
export const SLACK_SETUP_INTEGRATION = "EVENT_SLACK_SETUP_INTEGRATION";
export const SLACK_UPDATE_DEFAULT_CHANNEL =
  "EVENT_SLACK_UPDATE_DEFAULT_CHANNEL";

/* Bookmarking Events */
export const EVENT_BOOKMARK_CLICKED_MARKING = "CLICK_BOOKMARK";
export const EVENT_BOOKMARK_CLICKED_UNMARKING = "CLICK_UNBOOKMARK";
export const EVENT_BOOKMARK_LIMIT_REACHED = "EVENT_BOOKMARK_LIMIT_180";
export const EVENT_BOOKMARK_USED_FOR_NAVIGATION =
  "CLICK_BOOKMARK_USED_FOR_NAVIGATION";
