export const assetTypeList: {
    id: string
    label: string
    nameAttribute?: string
    qualifiedNameAttribute?: string
    parents?: string[]
    children?: string[]
    isDiscoverable?: boolean
    orderWeight?: number
    count?: number
    relationships?: string[]
}[] = [
    {
        id: 'Connection',
        label: 'Connection',
        nameAttribute: 'connectionName',
        qualifiedNameAttribute: 'connectionQualifiedName',
        parents: [],
        children: ['Column'],
        count: 0,
        relationships: [],
    },
    {
        id: 'Database',
        label: 'Database',
        nameAttribute: 'databaseName',
        qualifiedNameAttribute: 'databaseQualifiedName',
        parents: ['AtlanConnection'],
        children: ['Column'],
        isDiscoverable: false,
        count: 0,
        relationships: [],
    },
    {
        id: 'Schema',
        label: 'Schema',
        nameAttribute: 'schemaName',
        qualifiedNameAttribute: 'schemaQualifiedName',
        parents: ['AtlanConnection', 'AtlanDatabase'],
        children: ['Column'],
        isDiscoverable: false,
        count: 0,
        relationships: [],
    },
    {
        id: 'View',
        label: 'View',
        nameAttribute: 'viewName',
        qualifiedNameAttribute: 'viewQualifiedName',
        parents: ['Connection', 'Database', 'Schema'],
        children: ['Column'],
        isDiscoverable: true,
        orderWeight: 90,
        count: 0,
        relationships: [],
    },
    {
        id: 'Table',
        label: 'Table',
        nameAttribute: 'tableName',
        qualifiedNameAttribute: 'tableQualifiedName',
        parents: ['Connection', 'Database', 'Schema'],
        children: ['Column'],
        isDiscoverable: true,
        orderWeight: 100,
        count: 0,
        relationships: [],
    },
    {
        id: 'TablePartition',
        label: 'Partition',
        nameAttribute: 'partitionName',
        qualifiedNameAttribute: 'partitionQualifiedName',
        parents: ['Connection', 'Database', 'Schema'],
        children: ['Column'],
        isDiscoverable: true,
        orderWeight: 100,
        count: 0,
        relationships: [],
    },
    {
        id: 'MaterialisedView',
        label: 'Materialised View',
        nameAttribute: 'materialisedView',
        qualifiedNameAttribute: 'materialisedViewQualifiedName',
        parents: ['Connection', 'Database', 'Schema'],
        children: ['Column'],
        isDiscoverable: true,
        orderWeight: 100,
        count: 0,
        relationships: [],
    },
    {
        id: 'Column',
        label: 'Column',
        nameAttribute: '',
        qualifiedNameAttribute: 'databaseQualifiedName',
        parents: ['Connection', 'Database', 'Schema', 'Table', 'View'],
        children: [],
        isDiscoverable: true,
        orderWeight: 80,
        count: 0,
        relationships: [],
    },
    {
        id: 'Query',
        label: 'Query',
        nameAttribute: 'queryName',
        qualifiedNameAttribute: 'queryQualifiedName',
        parents: ['Connection', 'Database', 'Schema'],
        children: [],
        isDiscoverable: true,
        orderWeight: 70,
        count: 0,
        relationships: ['tables', 'views', 'columns'],
    },
    /*   {
        id: 'Folder',
        label: 'Folder',
        qualifiedNameAttribute: 'parentQualifiedName',
        parents: ['Connection', 'Database', 'Schema'],
        children: ['Query'],
        isDiscoverable: true,
        orderWeight: 60,
        count: 0,
    }, */
    {
        id: 'AtlasGlossaryTerm',
        label: 'Term',
        isDiscoverable: true,
        relationships: [],
    },
    {
        id: 'AtlasGlossaryCategory',
        label: 'Categories',
        isDiscoverable: true,
        relationships: [],
    },
    {
        id: 'TableauSite',
        label: 'Tableau Site',
        nameAttribute: 'siteName',
        isDiscoverable: true,
        parents: [],
        relationships: [],
    },
    {
        id: 'TableauProject',
        label: 'Tableau Project',
        nameAttribute: 'projectName',
        isDiscoverable: true,
        // in order of hierarchy
        parents: ['TableauProject', 'TableauSite'],
        relationships: [],
    },
    {
        id: 'TableauWorkbook',
        label: 'Tableau Workbook',
        nameAttribute: 'workbookName',
        isDiscoverable: true,
        parents: ['TableauProject'],
        relationships: [],
    },
    {
        id: 'TableauWorksheet',
        label: 'Tableau Worksheet',
        isDiscoverable: true,
        parents: ['TableauWorkbook'],
        relationships: [],
    },
    {
        id: 'TableauDashboard',
        label: 'Tableau Dashboard',
        isDiscoverable: true,
        parents: ['TableauWorkbook'],
        relationships: [],
    },
    {
        id: 'TableauDatasource',
        label: 'Tableau Datasource',
        nameAttribute: 'datasourceName',
        isDiscoverable: true,
        parents: ['TableauWorkbook'],
        relationships: [],
    },
    {
        id: 'TableauDatasourceField',
        label: 'Tableau Datasource Field',
        parents: ['TableauWorkbook'],
        relationships: [],
    },
    {
        id: 'TableauCalculatedField',
        label: 'Tableau Calculated Field',
        parents: ['TableauWorkbook'],
        relationships: [],
    },
    {
        id: 'PowerBIWorkspace',
        label: 'Power BI Workspace',
        isDiscoverable: true,
        parents: [],
        children: ['PowerBIDashboard'],
        relationships: ['reports', 'datasets', 'dashboards', 'dataflows'],
    },
    {
        id: 'PowerBIDashboard',
        label: 'Power BI Dashboard',
        isDiscoverable: true,
        parents: ['PowerBIWorkspace'],
        children: ['PowerBITile'],
        relationships: ['tiles', 'workspace'],
    },
    {
        id: 'PowerBIReport',
        label: 'Power BI Report',
        isDiscoverable: true,
        parents: ['PowerBIWorkspace'],
        children: ['PowerBIPage'],
        relationships: ['workspace', 'pages'],
    },
    {
        id: 'PowerBIDataset',
        label: 'Power BI Dataset',
        isDiscoverable: true,
        parents: ['PowerBIWorkspace'],
        children: ['PowerBIDatasource'],
        relationships: ['workspace', 'datasources'],
    },
    {
        id: 'PowerBIDataflow',
        label: 'Power BI Dataflow',
        isDiscoverable: true,
        parents: ['PowerBIWorkspace'],
        relationships: ['workspace'],
    },
    {
        id: 'PowerBITile',
        label: 'Power BI Tile',
        isDiscoverable: true,
        parents: ['PowerBIWorkspace', 'PowerBIDashboard'],
        relationships: ['dashboard'],
    },
    {
        id: 'PowerBIPage',
        label: 'Power BI Page',
        isDiscoverable: true,
        parents: ['PowerBIWorkspace', 'PowerBIReport'],
        relationships: ['report'],
    },
    {
        id: 'PowerBIDatasource',
        label: 'Power BI Datasource',
        isDiscoverable: true,
        parents: ['PowerBIWorkspace', 'PowerBIDataset'],
        relationships: ['datasets'],
    },
]
