import number from '~/assets/images/dataType/number.svg'
import float1 from '~/assets/images/dataType/float1.svg'
import boolean from '~/assets/images/dataType/boolean.svg'
import string from '~/assets/images/dataType/string.svg'
import date from '~/assets/images/dataType/date.svg'
import array from '~/assets/images/dataType/array.svg'
import struct from '~/assets/images/dataType/struct.svg'
import geography from '~/assets/images/dataType/geography.svg'
import variant from '~/assets/images/dataType/variant.svg'
import percent from '~/assets/images/dataType/percent.svg'
import enum2 from '~/assets/images/dataType/enum2.svg'
import lookup from '~/assets/images/dataType/lookup.svg'
import Super from '~/assets/images/dataType/super.svg'
import bits from '~/assets/images/dataType/bits.svg'
import spatial from '~/assets/images/dataType/spatial.svg'
import blob from '~/assets/images/dataType/blob.svg'

export const images = {
    Number: number,
    Decimal: float1,
    Boolean: boolean,
    Text: string,
    DateTime: date,
    Array: array,
    Object: struct,
    Geography: geography,
    Variant: variant,
    Bits: bits,
    Spatial: spatial,
    Blob: blob,
    Super,
}

export const dataTypeCategoryList = [
    {
        id: 'number',
        label: 'Number',
        type: [
            'NUMBER',
            'NUMERIC',
            'INT',
            'INT UNSIGNED',
            'INTEGER',
            'SMALLINT',
            'SMALLINT UNSIGNED',
            'MEDIUMINT',
            'MEDIUMINT UNSIGNED',
            'BIGINT',
            'BIGINT UNSIGNED',
            'INT4',
            'INT2',
            'INT64',
            'INT8',
            'TINYINT',
        ],
        image: number,
        imageText: 'number',
    },
    {
        id: 'decimal',
        label: 'Decimal',
        type: [
            'DECIMAL',
            'FLOAT',
            'FLOAT4',
            'FLOAT8',
            'FLOAT64',
            'DOUBLE',
            'DOUBLE PRECISION',
            'REAL',
            'PRIMITIVE_DOUBLE',
            'Currency',
        ],
        image: float1,
        imageText: 'float1',
    },
    {
        id: 'text',
        label: 'Text',
        type: [
            'CHAR',
            'CHARACTER',
            'STRING',
            'TEXT',
            'BINARY',
            'VARBINARY',
            'BPCHAR',
            'VARCHAR',
            'CHARACTER VARYING',
            'NCHAR',
            'AnyType',
            'Base64',
            'Byte',
            'DataCategoryGroupReference',
            'Email',
            'Encrypted String',
            'ID',
            'Master record',
            'Phone',
            'Textarea',
            'String',
            'URL',
            'MEDIUMTEXT',
            'LONGTEXT',
            'TINYTEXT',
            'SET',
            'BINARY VARYING',
            'VARBYTE',
        ],
        image: string,
        imageText: 'string',
    },
    {
        id: 'boolean',
        label: 'Boolean',
        type: ['BOOLEAN', 'BOOL'],
        image: boolean,
        imageText: 'boolean',
    },
    {
        id: 'dateTime',
        label: 'DateTime',
        type: [
            'DATE',
            'TIME',
            'TIMESTAMP',
            'TIMESTAMP_LTZ',
            'TIMESTAMP_NTZ',
            'IMESTAMP_TZ',
            'TIMESTAMPLTZ',
            'TIMESTAMPNTZ',
            'TIMESTAMPTZ',
            'TIMETZ',
            'DateTime',
        ],
        image: date,
        imageText: 'date',
    },
    {
        id: 'array',
        label: 'Array',
        type: ['ARRAY'],
        image: array,
        imageText: 'array',
    },
    {
        id: 'variant',
        label: 'Variant',
        type: ['VARIANT', 'ANY', 'HLLSKETCH'],
        image: variant,
        imageText: 'variant',
    },
    {
        id: 'object',
        label: 'Object',
        type: ['OBJECT', 'JSON', 'STRUCT', 'Combobox'],
        image: struct,
        imageText: 'struct',
    },
    {
        id: 'percent',
        label: 'Percent',
        type: ['Percent'],
        image: percent,
        imageText: 'percent',
    },
    {
        id: 'enum',
        label: 'Enum',
        type: ['Picklist', 'Multipicklist', 'ENUM'],
        image: enum2,
        imageText: 'enum',
    },
    {
        id: 'geography',
        label: 'Geography',
        type: ['GEOGRAPHY', 'Address', 'Location'],
        image: geography,
        imageText: 'geography',
    },
    {
        id: 'lookup',
        label: 'Lookup',
        type: ['Lookup', 'Reference'],
        image: lookup,
        imageText: 'lookup',
    },
    {
        id: 'super',
        label: 'super',
        type: ['Super'],
        image: Super,
        imageText: 'super',
    },
    {
        id: 'bits',
        label: 'bits',
        type: ['BIT'],
        image: bits,
        imageText: 'bits',
    },
    {
        id: 'spatial',
        label: 'spatial',
        type: [
            'GEOMETRY',
            'POINT',
            'LINESTRING',
            'POLYGON',
            'MULTIPOINT',
            'MULTILINESTRING',
            'MULTIPOLYGON',
            'GEOMETRYCOLLECTION',
        ],
        image: spatial,
        imageText: 'spatial',
    },
    {
        id: 'blob',
        label: 'blob',
        type: ['BLOB', 'TINYBLOB', 'MEDIUMBLOB', 'LONGBLOB'],
        image: blob,
        imageText: 'blob',
    },
]
