export const profileTabs = [
    {
        id: 'overview',
        label: 'Overview',
        component: 'overview',
        icon: 'Overview',
        activeIcon: 'OverviewActive',
        tooltip: 'Overview',
        scrubbed: false,
    },
    /* {
        id: 'columns',
        label: 'Columns',
        component: 'columns',
        includes: ['Table', 'View', 'MaterialisedViews', 'PartitionTable'],
        icon: 'Columns',
        tooltip: 'Columns',
    }, */
    {
        id: 'lineage',
        label: 'Lineage',
        component: 'lineage',
        excludes: [
            'Connection',
            'Database',
            'Schema',
            'Query',
            'QueryFolder',
            'AtlasGlossary',
            'AtlasGlossaryCategory',
            'AtlasGlossaryTerm',
        ],
        icon: 'Lineage',
        tooltip: 'Lineage',
        scrubbed: true,
    },
    /*  {
        id: 'queries',
        label: 'Queries',
        component: 'queries',
        includes: ['Table', 'View', 'MaterialisedViews', 'PartitionTable'],
        icon: 'Queries',
        tooltip: 'Queries',
        scrubbed: false,
    }, */
    {
        id: 'linkedAssets',
        label: 'Linked Assets',
        component: 'linkedAssets',
        includes: ['AtlasGlossaryTerm'],
        icon: 'LinkedAssets',
        tooltip: 'Linked Assets',
        scrubbed: false,
    },
    {
        id: 'termsAndCategories',
        label: 'Terms and Categories',
        component: 'termsAndCategories',
        includes: ['AtlasGlossary', 'AtlasGlossaryCategory'],
        icon: 'TermsAndCategories',
        tooltip: 'Terms and Categories',
        scrubbed: false,
    },
]
