export const ConnectionAttributes = [
  "allowPreview",
  "allowQuery",
  "botQualifiedName",
  "botVersion",
  "category",
  "description",
  "host",
  "extra",
  "port",
  "ownerUsers",
  "ownerGroups",
  "integrationName",
  "integrationCredentialQualifiedName",
];

export const CredentialAttributes = [
  "authType"
];


export const BaseAttributes = [
  "__timestamp",
  "__modificationTimestamp",
  "__modifiedBy",
  "__createdBy",
  "__state",
  "__guid",
  "__historicalGuids",
  "__classificationsText",
  "__classificationNames",
  "__propagatedClassificationNames",
  "__customAttributes",
  "__labels"
]

export const GlossaryAttributes = [];


export const BotsAttributes = [
  "category",
  "config",
  "description",
  "marketplaceLink",
  "name",
  "subCategory",
  "supportLink",
  "templateName",
  "integrationName",
  "version",
  "logo",
];

export const BasicSearchAttributes = [
  "__timestamp",
  "__modificationTimestamp",
  "__modifiedBy",
  "__createdBy",
  "__state",
  "__guid",
  "__historicalGuids",
  "__classificationsText",
  "__classificationNames",
  "__propagatedClassificationNames",
  "__customAttributes",
  "__labels",
  "name",
  "displayName",
  "description",
  "displayDescription",
  "userDescription",
  "meanings",
  "tenantId",
  "assetStatus",
  "assetStatusUpdatedAt",
  "assetStatusUpdatedBy",
  "assetStatusMessage",
  "connectionLastSyncedAt",
  "connectionQualifiedName",
  "rowCount",
  "columnCount",
  "subType",
  "image",
  "meanings.description",
  "sourceRefreshFrequency",
  "sourceCreatedBy",
  "sourceUpdatedAt",
  "sourceUpdatedBy",
  "databaseCount",
  "databaseCrawledCount",
  "schemaCount",
  "schemaCrawledCount",
  "tableCount",
  "tableCrawledCount",
  "dataType",
  "lastUpdatedByJob",
  "category",
  "integrationName",
  "host",
  "botQualifiedName",
  "schemaName",
  "databaseName",
  "logo",
  "viewDefinition",
  "popularityScore",
  "readers",
  "sourceViewCount",
  "integrationCredentialQualifiedName",
  "connectionName",
];
