export const summaryVariants = [
    {
        id: 'table',
        label: 'Table',
        components: ['Rows', 'Columns', 'Connection'],
        includes: ['Table', 'PartitionTable'],
    },
    {
        id: 'view',
        label: 'View',
        components: ['Definition', 'Columns', 'Connection'],
        includes: ['View', 'MaterialisedViews'],
    },
    {
        id: 'glossary',
        label: 'Glossary',
        components: ['TermsCount', 'CategoriesCount'],
        includes: ['AtlasGlossary'],
    },
    {
        id: 'category',
        label: 'Category',
        components: ['ParentGlossary', 'TermsCount'],
        includes: ['AtlasGlossaryCategory'],
    },
    {
        id: 'term',
        label: 'Term',
        components: ['ParentGlossary', 'Categories'],
        includes: ['AtlasGlossaryTerm'],
    },
    {
        id: 'workspace',
        label: 'Workspace',
        components: ['WorkspaceRelationsCount', 'Connection'],
        includes: ['PowerBIWorkspace'],
    },
    {
        id: 'powerBIDatasource',
        label: 'Datasource',
        components: ['ParentDataset', 'Connection'],
        includes: ['PowerBIDatasource'],
    },
    {
        id: 'dataset',
        label: 'Dataset',
        components: ['ParentWorkspace', 'Connection'],
        includes: ['PowerBIDataset'],
    },
    {
        id: 'dataflow',
        label: 'Dataflow',
        components: ['ParentWorkspace', 'Connection'],
        includes: ['PowerBIDataflow'],
    },
    {
        id: 'report',
        label: 'Report',
        components: ['ParentWorkspace', 'Pages', 'Connection'],
        includes: ['PowerBIReport'],
    },
    {
        id: 'powerBIDashboard',
        label: 'Dashboard',
        components: ['ParentWorkspace', 'Tiles', 'Connection'],
        includes: ['PowerBIDashboard'],
    },
    {
        id: 'page',
        label: 'Page',
        components: ['ParentReport', 'Connection'],
        includes: ['PowerBIPage'],
    },
    {
        id: 'tile',
        label: 'Tile',
        components: ['ParentDashboard', 'Connection'],
        includes: ['PowerBITile'],
    },
    {
        id: 'site',
        label: 'Site',
        components: ['Connection'],
        includes: ['TableauSite'],
    },
    {
        id: 'project',
        label: 'Project',
        components: ['ParentSite', 'Connection'],
        includes: ['TableauProject'],
    },
    {
        id: 'workbook',
        label: 'Workbook',
        components: ['ParentProject', 'Connection'],
        includes: ['TableauWorkbook'],
    },
    {
        id: 'worksheet',
        label: 'Worksheet',
        components: ['ParentWorkbook', 'Connection'],
        includes: ['TableauWorksheet'],
    },
    {
        id: 'tableauDashboard',
        label: 'Dashboard',
        components: ['ParentWorkbook', 'Connection'],
        includes: ['TableauDashboard'],
    },
    {
        id: 'tableauDatasource',
        label: 'Datasource',
        components: ['ParentWorkbook', 'Connection'],
        includes: ['TableauDatasource'],
    },
    {
        id: 'calculatedField',
        label: 'Calculated Field',
        components: ['ParentDatasource', 'Connection'],
        includes: ['TableauCalculatedField'],
    },
    {
        id: 'datasourceField',
        label: 'Datasource Field',
        components: ['ParentDatasource', 'Connection'],
        includes: ['TableauDatasourceField'],
    },
    {
        id: 'flow',
        label: 'Flow',
        components: ['ParentProject', 'Connection'],
        includes: ['TableauFlow'],
    },
    {
        id: 'metric',
        label: 'Metric',
        components: ['ParentProject', 'Connection'],
        includes: ['TableauMetric'],
    },
]
