export const queryLogsFilter = [
    {
        id: 'queryStatus',
        label: 'STATUS',
        component: 'queryStatus',
        overallCondition: 'OR',
        attributes: [],
        isDeleted: false,
        isDisabled: false,
        exclude: false,
        class: 'bg-transparent',
    },
    {
        id: 'users',
        label: 'Users',
        component: 'owners',
        overallCondition: 'OR',
        attributes: [],
        isDeleted: false,
        isDisabled: false,
        exclude: false,
        propsToComponent: {
            showNone: false,
            hideDisabledTabs: true,
            enableTabs: ['users'],
        },
        class: 'bg-transparent',
    },
]
export const accessLogsFilter = [
    {
        id: 'logAction',
        label: 'Action',
        component: 'logAction',
        overallCondition: 'OR',
        attributes: [],
        isDeleted: false,
        isDisabled: false,
        exclude: false,
        class: 'bg-transparent',
    },
    {
        id: 'logStatus',
        label: 'Status',
        component: 'logStatus',
        overallCondition: 'OR',
        attributes: [],
        isDeleted: false,
        isDisabled: false,
        exclude: false,
        class: 'bg-transparent',
    },
    {
        id: 'userType',
        label: 'User Type',
        component: 'userTypes',
        overallCondition: 'OR',
        attributes: [],
        isDeleted: false,
        isDisabled: false,
        exclude: false,
        class: 'bg-transparent',
    },
    {
        id: 'users',
        label: 'Users',
        component: 'owners',
        overallCondition: 'OR',
        attributes: [],
        isDeleted: false,
        isDisabled: false,
        exclude: false,
        propsToComponent: {
            showNone: false,
            hideDisabledTabs: true,
            enableTabs: ['users'],
        },
        class: 'bg-transparent',
    },
    {
        id: 'properties',
        label: 'Properties',
        component: 'properties',
        attributes: [
            {
                name: 'resource.keyword',
                displayName: 'Qualified Name',
                description: 'Unique name for asset',
                typeName: 'string',
                isMandatory: true,
            },
        ],
        overallCondition: 'OR',
        isDeleted: false,
        isDisabled: false,
        exclude: false,
    },
]

export const requestFilter = [
    {
        id: 'users',
        label: 'Requestor',
        component: 'owners',
        overallCondition: 'OR',
        attributes: [],
        isDeleted: false,
        isDisabled: false,
        exclude: false,
        propsToComponent: {
            showNone: false,
            hideDisabledTabs: true,
            enableTabs: ['users'],
        },
        class: 'bg-transparent',
    },
    {
        id: 'queryStatus',
        label: 'STATUS',
        component: 'queryStatus',
        overallCondition: 'OR',
        attributes: [],
        isDeleted: false,
        isDisabled: false,
        exclude: false,
        class: 'bg-transparent',
    },
    {
        id: 'terms',
        label: 'Terms',
        component: 'governance',
        overallCondition: 'OR',
        attributes: [],
        isDeleted: false,
        isDisabled: false,
        exclude: false,
    },
    {
        id: '__traitNames',
        label: 'Classifications',
        component: 'classifications',
        overallCondition: 'OR',
        attributes: [],
        isDeleted: false,
        isDisabled: false,
        exclude: false,
    },
]