export enum MutationTypes {
  SET_CLASSIFICATIONS = "SET_CLASSIFICATIONS",
  CREATE_CLASSIFICATION = "CREATE_CLASSIFICATION",
  CREATE_CLASSIFICATION_STATUS = "CREATE_CLASSIFICATION_STATUS",
  SET_CLASSIFICATIONS_STATUS = "SET_CLASSIFICATIONS_STATUS",
  UPDATE_CLASSIFICATION_LIST_BY_ID = "UPDATE_CLASSIFICATION_LIST_BY_ID",
  SET_CLASSIFICATION_TREE = "SET_CLASSIFICATION_TREE",
  SET_FILTERED_CLASSIFICATION_TREE = "SET_FILTERED_CLASSIFICATION_TREE",
}
